import { ProgrammingProps } from "../../components/sections/Programming/types";

export const programmingContent: ProgrammingProps[] = [
  {
    name: "Abertura oficial",
    image: 'minister',
    imageDescription: "OnovoLab",
    bio: "",
    author: "ONOVOLAB",
    date: "28/08",
    time: "19h - 21h30",
    link: "https://www.sympla.com.br/abertura-da-iv-semana-da-computacao-wecomp-do-ifsp-sao-carlos__2114909",
    vacancies: 0,
    location: "ONOVOLAB",
    description:
      "A abertura oficial da IV Wecomp acontecerá no ONOVOLAB e contará com a presença de empresas parceiras, uma mesa redonda com o tema 'IA generativa, mercado de trabalho e a carreira dos (novos) desenvolvedores' e uma confraternização. Não perca!",
    typeEvent: "Opening",
    classification: "Basic",
    status: "Closed",
  },
  {
    name: "Como é o dia-a-dia de um QA?",
    image: 'minister',
    imageDescription: "Cerminaro",
    bio: "Leonardo Cerminaro é formado em Análise e Desenvolvimento de Sistemas pelo IFSP São Carlos e trabalha como Senior Quality Assurance Engineer na X-Team. Possui certificações de teste de software CTFL-AT e CTFL da BSTQB e ampla experiência em qualidade de software.",
    author: "Leonardo Cerminaro",
    date: "28/08",
    time: "8h - 12h",
    link: "https://forms.gle/DLzmDh1j7UDSu7f28",
    vacancies: 0,
    location: "IFSP",
    description:
      "Nesse workshop, serão demonstradas de maneira prática algumas atividades rotineiras de um profissional que trabalha como QA. Iniciaremos a parte de criação de casos de teste, execução dos casos de testes criados, explicação de conceitos de Engenharia de Software na prática e criação dos testes automatizados utilizando Javascript e Cypress.",
    typeEvent: "Course",
    classification: "Basic",
    status: "Closed",
  },
  {
    name: "Criando um aplicativo de clima com Flutter",
    image: 'minister',
    imageDescription: "Davi Guelfi Erba",
    bio: "Davi é desenvolvedor full-stack com foco em front-end na Monitora, organizador do OpenSanca, apaixonado por carro, tecnologia e aleatoriedades.",
    author: "Davi Guelfi Erba",
    date: "28/08",
    time: "8h - 12h",
    link: "https://forms.gle/f3bwWbb9V6aAJvnz6",
    vacancies: 0,
    location: "IFSP",
    description:
      "Neste minicurso os participantes irão aprender como criar um aplicativo para visualizar dados meteorológicos utilizando o Flutter. É um curso básico para os que querem conhecer essa tecnologia de desenvolvimento híbrida que é uma das mais utilizadas no mercado.",
    typeEvent: "Course",
    classification: "Basic",
    status: "Closed",
  },
  {
    name: "Jornada Cloud Native",
    image: 'minister',
    imageDescription: "Jornada Cloud Native",
    bio: "Henrique Lima Margarido e Augusto Moreto Barros são especialistas em DevOps na Minsait, com experiência em Kubernetes, CI/CD, automação de infraestrutura, observabilidade e nuvem (AWS, Azure).",
    author: "Henrique Margarido e Augusto Barros",
    date: "29/08",
    time: "8h - 12h",
    link: "https://forms.gle/7BMKazi7Q4d9GPQy6",
    vacancies: 0,
    location: "IFSP",
    description:
      "Aprenda as melhores práticas para modernizar sua infraestrutura com Cloud Native, utilizando contêineres, orquestração e observabilidade com OpenTelemetry e Grafana Stack. Explore práticas para coletar, analisar e visualizar dados de sistemas complexos.",
    typeEvent: "Course",
    classification: "Intermediary",
    status: "Closed",
  },
  {
    name: "Explorando a arquitetura MVVM e Consumo de API em Desenvolvimento Mobile",
    image: 'minister',
    imageDescription: "Geovanna Martins e Gustavo Feliciano",
    bio: "Geovana Martins é desenvolvedora Android na Santander F1RST e Gustavo Feliciano é Engenheiro iOS na F1RST, ambos com formação em tecnologia e experiência em desenvolvimento mobile.",
    author: "Geovanna Martins e Gustavo Feliciano",
    date: "29/08",
    time: "9h - 12h",
    link: "https://forms.gle/YYBTb7h1E7YEysZy8",
    vacancies: 0,
    location: "IFSP",
    description:
      "Curso prático focado em desenvolvimento Android e iOS. Inclui arquitetura MVVM, consumo de API com Swift e Kotlin, e construção de apps utilizando serviços como o ViaCEP.",
    typeEvent: "Course",
    classification: "Intermediary",
    status: "Closed",
  },
  {
    name: "Ciência de dados aplicada a imagens",
    image: 'minister',
    imageDescription: "Ciência de dados aplicada a imagens",
    bio: "Jorge Franco e Augusto Nunes são estudantes e pesquisadores com experiência em IA, machine learning e ciência de dados, com passagens por USP, Embrapa e grupos como o DATA.",
    author: "Jorge Luiz Franco e Augusto Nunes",
    date: "29/08",
    time: "14h - 18h",
    link: "https://forms.gle/ZfiRBYJdsKDdEmjS6",
    vacancies: 0,
    location: "IFSP",
    description:
      "Neste curso serão apresentados os conceitos básicos de um pipeline de ciência de dados aplicado a imagens, incluindo pré-processamento, modelagem e avaliação, com foco em visão computacional. É necessário conhecimento em Python.",
    typeEvent: "Course",
    classification: "Basic",
    status: "Closed",
  },
];

export default programmingContent;
